spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: root
  







# spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
# spring.datasource.username=root
# spring.datasource.password=root

# resilience4j.circuitbreaker.instances.customerService.failureRateThreshold=50
# resilience4j.circuitbreaker.instances.customerService.ringBufferSizeInClosedState=5
# resilience4j.circuitbreaker.instances.customerService.ringBufferSizeInHalfOpenState=3
# resilience4j.circuitbreaker.instances.customerService.waitDurationInOpenState=20s
# resilience4j.circuitbreaker.instances.customerService.automaticTransitionFromOpenToHalfOpenEnabled=true
