spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
  username: root
  password: root
  
resilience4j.circuitbreaker: 
    instances: 
        customerService:            
            failureRateThreshold: 50 
            ringBufferSizeInClosedState: 5 
            ringBufferSizeInHalfOpenState: 3 
            waitDurationInOpenState: 30s 
            automaticTransitionFromOpenToHalfOpenEnabled: true 







# spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
# spring.datasource.username=root
# spring.datasource.password=root

# resilience4j.circuitbreaker.instances.customerService.failureRateThreshold=50
# resilience4j.circuitbreaker.instances.customerService.ringBufferSizeInClosedState=5
# resilience4j.circuitbreaker.instances.customerService.ringBufferSizeInHalfOpenState=3
# resilience4j.circuitbreaker.instances.customerService.waitDurationInOpenState=20s
# resilience4j.circuitbreaker.instances.customerService.automaticTransitionFromOpenToHalfOpenEnabled=true
